Practice Fro Nominol Encoding

In [85]:
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
df = sns.load_dataset('tips')
df[['tip']]#.count()

df[df['tip']==1.0]

# for group , name in df.groupby('tip'):
#     print(group)

     total_bill  tip     sex smoker  day    time  size
67         3.07  1.0  Female    Yes  Sat  Dinner     1
92         5.75  1.0  Female    Yes  Fri  Dinner     2
111        7.25  1.0  Female     No  Sat  Dinner     1
236       12.60  1.0    Male    Yes  Sat  Dinner     2

In [ ]:
encoder = OneHotEncoder()

In [92]:
encoded = encoder.fit_transform(df[['tip']]).toarray()
encoded = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

ouptut = pd.concat([df['tip'],encoded],axis=1)
ouptut

,tip,tip_1.0,tip_1.01,tip_1.1,tip_1.17,tip_1.25,tip_1.32,tip_1.36,tip_1.44,tip_1.45,...,tip_5.65,tip_5.85,tip_5.92,tip_6.0,tip_6.5,tip_6.7,tip_6.73,tip_7.58,tip_9.0,tip_10.0
0,1.01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.61,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,5.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
240,2.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
241,2.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
242,1.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
243,3.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Ordinal Encoding:

In [106]:
mean_total_bill = df.groupby('time')['total_bill'].mean().to_dict()

df['mean_total_bill'] = df['time'].map(mean_total_bill)
print(df[['time','total_bill','mean_total_bill']])

       time  total_bill mean_total_bill
0    Dinner       16.99       20.797159
1    Dinner       10.34       20.797159
2    Dinner       21.01       20.797159
3    Dinner       23.68       20.797159
4    Dinner       24.59       20.797159
..      ...         ...             ...
239  Dinner       29.03       20.797159
240  Dinner       27.18       20.797159
241  Dinner       22.67       20.797159
242  Dinner       17.82       20.797159
243  Dinner       18.78       20.797159

[244 rows x 3 columns]

C:\Users\GOVE-LAP-15\AppData\Local\Temp\ipykernel_27572\4204536836.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_total_bill = df.groupby('time')['total_bill'].mean().to_dict()